name: the_bar_gym
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:


  js: ^0.6.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  jiffy: ^4.1.0
  cached_network_image: ^3.1.0
  flutter_barcode_scanner: ^2.0.0
  crypto: ^3.0.1
  provider: ^6.0.2
  qr_code_scanner: ^0.6.1
  url_launcher: ^6.0.3
  material_dialogs: ^1.1.1
  video_player: ^2.2.13
  shared_preferences: ^2.0.12
  flutter_speed_dial: ^5.0.0+1
  intl: ^0.17.0
  moor_flutter: ^4.0.0
  path_provider: ^2.0.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  file_picker: ^4.3.3
  firebase_storage: ^10.2.6
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+5


  equatable: ^2.0.3

  validators: ^3.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  moor_generator: ^4.6.0
  build_runner: ^2.1.7


flutter:


  uses-material-design: true

  assets:
    - assets/images/no_data.png
    - images/
    - images/chest/
    - images/back/
    - images/legs/
